services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - 'gunicorn'
      - 'recipesite.wsgi:application'
      - '--bind'
      - '0.0.0.0:8000'

    ports:
      - '80:8000'
    restart: always
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '200k'
    volumes:
      - ./recipesite/database:/app/database


