# Generated by Django 5.1.3 on 2024-11-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
