# Generated by Django 5.1.3 on 2024-12-11 19:03

import recipeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0008_alter_ingredient_options_recipe_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=recipeapp.models.ingredient_preview_directory_path),
        ),
    ]
