# Generated by Django 5.1.3 on 2024-12-11 19:38

import django.db.models.deletion
import recipeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0009_ingredient_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recipeapp.models.ingredient_images_directory_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipeapp.ingredient')),
            ],
        ),
    ]
