# Generated by Django 5.1.3 on 2024-12-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0010_ingredientimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientimage',
            old_name='product',
            new_name='ingredient',
        ),
    ]
