# Generated by Django 5.1.3 on 2024-12-26 17:58

import recipeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0012_alter_ingredient_description_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_image',
            field=models.FileField(blank=True, null=True, upload_to=recipeapp.models.recipe_images_directory_path),
        ),
    ]
