# Generated by Django 5.1.3 on 2024-12-26 18:27

import django.db.models.deletion
import recipeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0013_alter_recipe_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dish_image',
        ),
        migrations.AddField(
            model_name='recipe',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to=recipeapp.models.recipe_preview_directory_path),
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recipeapp.models.recipe_images_directory_path)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipeapp.recipe')),
            ],
        ),
    ]
