# Generated by Django 5.1.3 on 2024-12-27 15:00

import recipeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0014_remove_recipe_dish_image_recipe_preview_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=recipeapp.models.recipe_preview_directory_path),
        ),
    ]
